### ISSUE TITLE
B: Shelby Financials - Inappropriately Assigning Account Sub to Debit Account

### ISSUE THREAD

**Issue by guymaness2** [KingdomFirst/RockBlocks#119]
# Expected Behavior

The Shelby Financials plugin allows for setting an "Account Sub" attribute on a financial account to be used for properly formatting sub accounts. Since Shelby Financials supports sub accounts structured this way for both Balance Sheet accounts and Income/Expense accounts, it would be expected that the plugin could properly handle both.

# Current Behavior

There is currently only one "Account Sub" attribute. If a value is put in this attribute for a particular Rock account, the Account Sub is added to both the Revenue and Debit account attribute values when creating the export file. This results in an error when importing into Shelby Financials if either the Debit or Revenue account do not have a matching sub account.

# Failure Information (for bugs)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue. 

1. Configure a Financial Account in Rock with valid Revenue Account, Debit Account, and Account Sub values.
2. Run either BatchesToJournal or BatchToJournal plugin block for Shelby Financials to export a journal file.
3. Note the exported file has set the Account Sub value for both the Debit (Debit Account) and Credit (Revenue Account) entry lines.

Dev Notes: The issue lies in the rocks.kfs.ShelbyFinancials.SFJournal.GenerateLineItems() method. As the GL lines are being generated, the individual "creditLine" and "debitLine" entries are both are having their AccountSub property set to provided attribute value. Recommended fix is to provide an additional Account Sub attribute (making one for Revenue and one for Debit) so the values can be set independently in the journal entry lines.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Rock Version: 1.12.8
* SQL Server Version:  
* Windows Version:  10 Pro

**Comment by nateh777** [comment]
Fixed in https://github.com/KingdomFirst/RockAssemblies/pull/100
