### ISSUE TITLE
B: Advancved Group Finder - Multiple Attribute Issues

### ISSUE THREAD

**Issue by asdf1nit** [KingdomFirst/RockBlocks#149]
_Block Name:_ Group Finder KFS

# Expected Behavior

When you have multiple group attribute filters set on the block, you should be able to select from only one group of filters and have a filtered set of groups returned.

# Current Behavior

If you set multiple filters, and one is a gender type filter, search  will not work without setting a gender. See example in video walk through.  https://soapbox.wistia.com/videos/PPsr5jmfd6

I tried different combinations of attribute filter types, single select, text, Single Select(Defined Type Group Attribute Value) and they all work fine when combined. The gender filter that we use for men's or women's classes is the only one I've had issues with.

# Failure Information (for bugs)

Search will not work when a gender filter is unset\default this effects page parameter filters as well

## Steps to Reproduce

Please provide detailed steps for reproducing the issue. 

1. Add a gender typed group attribute to a group type for signups.
2. Set the new attribute to male or female on a few groups
3. Add the gender filter on the block settings by checking the box next to the Gender group attribute filter
4. Add another Group attribute filter to the block settings
5. Try and search without setting the gender

## Context

* Rock Version: 15.1
* Bulldozer Version: (for Bulldozer only)
* SQL Server Version: Azure
* Windows Version: Server 2016

## Failure Logs

No logs or snippets, demo video linked above

**Comment by nateh777** [comment]
hey @asdf1nit, I am sorry you are experiencing an issue with our Advanced Group Finder. I went to confirm this bug today and I cannot seem to reproduce this issue no matter what version I test this on in our Advanced Group Finder. I saw it obviously not working in your video, so it must be something. Can you make sure your plugin is up to date from the Rock Shop? Also, can you test your groups with the core group finder and see if this happens with their version as well? I am curious if there is a specific data case that I am not producing. If you can reproduce it with the core group finder perhaps you can setup a scenario on RockSolidChurchdemo.com that I can reproduce?

**Comment by asdf1nit** [comment]
@nateh777 I'll dig in a little more and see about getting a demo set up on the rock pre alpha site (it's not wiped nightly). Looking back at my group type configuration, this "small group" group type inherits from the "Check-in by age" group type. Maybe the inheritance has something to do with it? I'll mimic my setup on the demo.

**Comment by asdf1nit** [comment]
@nateh777 You can close this issue. Since this plugin is not installed on the demo server, I can't duplicate it there for you. The bug is also in core so it should be fixed upstream.
