### ISSUE TITLE
B: Group Finder 

### ISSUE THREAD

**Issue by KelleyLangkamp** [KingdomFirst/RockBlocks#154]
# Expected Behavior

The **Hide Attribute Filter Values** to hide the checked values.

# Current Behavior

The values still shows in the filters. In the case of a defined type, the only way to hide the value is to inactive it. 

## Steps to Reproduce

Please provide detailed steps for reproducing the issue. 

1. Have a defined type group attribute
2. In the Hide Attribute Filter Values setting, check one of the boxes to hide that filter value.
3. Value still appears

## Context
<img width="426" alt="Snag_21fb3243" src="https://github.com/KingdomFirst/RockBlocks/assets/12735965/395c6f7a-bd6f-45e9-9e06-bd802cbb57ec">

* Rock Version: 13.7

**Comment by nateh777** [comment]
@KelleyLangkamp I am unable to reproduce on v14-16 with a defined type. I was able to reproduce it with a single-select attribute though, can you clarify that it was Group Finder 1.6 and a defined type/value or if it was a single/multi-select attribute. Or let me know where I can see it being produced?

**Comment by nateh777** [comment]
I believe this was not necessarily an issue but a misunderstanding in how the block worked. If you notice in the screenshot there are 2 different values with the same title "New Believers" one is checked, one is not. Unfortunately, it was not clear with which attribute the values came from, in a new update there will be a bit more clarity, but I would not necessarily call it an issue. I am going to close for now unless anyone disagrees, in the future version I will still tag this issue with the clarification mod.
