### ISSUE TITLE
B: Batch to Intacct is not exporting refunded fees properly

### ISSUE THREAD

**Issue by carlatKFS** [KingdomFirst/RockBlocks#166]
# Expected Behavior

Refunding fees should export correctly

# Current Behavior

Client upgraded to v16+ and there are some minor glitches. The fees on the Refunds are not processing correctly and the audit log shows “out of balance”.

# Failure Information (for bugs)

Pull request referenced in comment: [Intacct Bug Fix - Handle Refund transaction fees by nateh777 · Pull Request #82 · KingdomFirst/RockAssemblies (github.com)](https://github.com/KingdomFirst/RockAssemblies/pull/82/files#) all the way from 2022, long before the grouping changes that seem to have introduced this issue again. 

## Failure Logs

![image001 (7d9a6cc9-16a2-4a30-89c6-a624ea9b43db)](https://github.com/KingdomFirst/RockBlocks/assets/55153079/ad89f494-2b29-480d-be00-62c86e117b02)

## Reported by
Champion Forest

**Comment by nateh777** [comment]
Confirmed. 

**Steps to Reproduce:**
1. Ensure you have a batch that exports with transaction fee's (Gateway is configured to export transaction fees, net or gross) and you have a transaction attached to said Gateway with a Fee Amount)
2. Modify a fee to be a negative fee, i.e. a refund
3. Generate attached error.

**Comment by nateh777** [comment]
Fixed in https://github.com/KingdomFirst/RockAssemblies/pull/148
