### ISSUE TITLE
B: Batch to Intacct is not working properly with provided custom dimensions

### ISSUE THREAD

**Issue by carlatKFS** [KingdomFirst/RockBlocks#167]
# Expected Behavior

Batches with event codes would export

# Current Behavior

We continue to have 1 batch in Rock (for Mission trip) that we are unable to export. After further research, it appears that it’s not recognizing the event code.

# Failure Information (for bugs)

![Error Message](https://github.com/KingdomFirst/RockBlocks/assets/55153079/fe8529d0-20e1-4024-9167-bbca2b2ea5f6)

## Context

The specific client scenario involves checks, not credit cards. 

## Reported by
Champion Forest

**Comment by nateh777** [comment]
Unable to confirm with our own tests. Ended up being multiple attributes were setup with the same last part of the attribute key causing a conflict with the real value which was the "ID" of the object, the other attribute was the project code which is not valid on the Intacct side.
