### ISSUE TITLE
B: Steps to Care - Worker Assignment Issue

### ISSUE THREAD

**Issue by carlatKFS** [KingdomFirst/RockBlocks#169]
# Expected Behavior

Workers would consistently be assigned.

# Current Behavior

Added a request, auto assigned a worker. Added a second request, no worker assigned at all.

## Steps to Reproduce

1. Setup a Rock instance that does not have "Campus" enabled or just 1 Campus. 
2. Test Steps to care Worker assignment. 

## Context
Check to see if issue applies to people that have a Campus listed or not, or both.
Logging has been turned on. Waiting for more data.

**Comment by nateh777** [comment]
Unable to reproduce, if someone else reports it we can reopen when we have better steps to reproduce it.
