### ISSUE TITLE
B: Scheduled Group SMS sending duplicates

### ISSUE THREAD

**Issue by KelleyLangkamp** [KingdomFirst/RockBlocks#21]
# Expected Behavior

The job should be sending out 1 message per group member

# Current Behavior

All group members are getting 2 messages, randomly. Sometimes just 1 message, sometimes 2.

## Context

Biltmore is seeing that the job randomly sends multiple messages. The job completes successfully, it just sends 8 messages instead of 4. The job is running at 8 am and again at 8 pm every day.

![image](https://user-images.githubusercontent.com/12735965/87955257-17594e80-ca73-11ea-9c43-5ca4e02dbc3f.png)

* Rock Version: 10.2

**Comment by nateh777** [comment]
@KelleyLangkamp can you attempt to reproduce and confirm, if possible, to document steps before a dev can review? We can still review, but if it is confirmed it will be much quicker and we can prioritize better.
