### ISSUE TITLE
B: Flat File Importer: Exception thrown when SP isn't set (Repo #11)

### ISSUE THREAD

**Issue by carlatKFS** [KingdomFirst/RockBlocks#26]
# Expected Behavior

1) When a SP isn't set in the block setting, the current code is supposed to ignore the Run SQL step.
2) Alphabetically order the list of procedures in the block setting.

# Current Behavior

1) Currently it runs the step anyway with a blank value which throws an exception.
2) List of procedures is not in alphabetical order.

**Comment by KelleyLangkamp** [comment]
This was fixed at some point and the issue just wasn't closed.
